name: "(Release) Release dev container templates"
on:
  workflow_dispatch:
  push:
    branches:
      - release/devcontainers/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: "Publish"
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./alibaba"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}